[sqlfluff]
dialect = tsql
encoding = utf-8
max_line_length = 120

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:indentation]
indented_joins = True
indented_using_on = True
template_blocks_indent = True
indent_unit = space
tab_space_size = 4

[sqlfluff:rules:layout.commas]
comma_style = leading

[sqlfluff:rules:layout.select_targets]
allow_leading_comma = true
indent_with_tabs = false
